server:
  port: 8081
spring:
  application:
    name: ura-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/camping_record
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  typeAliasesPackage: com.example.campingrecord.mapper
  mapperLocations: classpath:mapper/*.xml

oss:
  endpoint: https://oss-cn-zhangjiakou.aliyuncs.com
#    endpoint: https://oss-cn-zhangjiakou-internal.aliyuncs.com
  accessKeyId: accessKeyId
  accessKeySecret: accessKeySecret
  bucketName: camping
  path: camping/