server:
  port: 8081
spring:
  application:
    name: ura-service
  datasource:
    url: jdbc:mysql://39.99.235.0:3306/camping_record
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: akcxakakc1

mybatis:
  typeAliasesPackage: com.example.campingrecord.mapper
  mapperLocations: classpath:mapper/*.xml

oss:
  endpoint: https://oss-cn-zhangjiakou.aliyuncs.com
#    endpoint: https://oss-cn-zhangjiakou-internal.aliyuncs.com
  accessKeyId: LTAI5tQcQRktQcnjEZVapBSv
  accessKeySecret: Blo4BmDaU7gBwJz4PPO5mndvf5JDGb
  bucketName: camping
  path: camping/